@url = http://localhost:8787
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyaWZhc2VsbGEiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3NzAwMjI2NDV9.tBfiluyOdOF0IgBYVHCpjCtLL-KCYf85fTqfEDqUIsE
@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc2NzYyOTYxNH0.-obv_Lsnsd7ckFKNYAlSYH0bIN7z8WNaGUb5Dr3CuYg

### REGISTER
POST {{url}}/auth/register
Content-Type: application/json

{
  "username": "rifasella",
  "password": "rahasia"
}

### LOGIN
POST {{url}}/auth/login
Content-Type: application/json

{
  "username": "rifasella",
  "password": null
}

### GET MY PROFILE
GET {{url}}/user/me
Authorization: Bearer {{token}}

### GET ALL USER (admin)
GET {{url}}/user?limit=2
Authorization: Bearer {{tokenAdmin}}

### GET PERSON BY ID (login)
GET {{url}}/person/5
Authorization: Bearer {{token}}

### GET ALL PERSON + FILTER
GET {{url}}/person?page=2&per_page=5&address=pasirmakam

### ADD NEW PERSON 
POST {{url}}/person
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "kanta",
  "fullname": "Sukanta",
  "address": "kadaung",
  "gender": "male",
  "birthDate": "1975-07-16"
}

### ADD MARIAGES
POST {{url}}/mariage
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "husband_id": 9,
  "wife_id": 5
}

### ADD DESCENDANT
POST {{url}}/descendant
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "personId": 8,
  "mariageId": 2
}

### GET PARENTS
GET {{url}}/person/8/parents
Authorization: Bearer {{token}}

### GET CHILDREN
GET {{url}}/person/1/children
Authorization: Bearer {{token}}
